version: '3.4'

services:
  db:
    image: postgres:latest
    container_name: sigbba-pg-container
    ports:
      - 5431:5432/tcp
    environment:
      POSTGRES_DB: sigbba
      POSTGRES_USER: root
      POSTGRES_PASSWORD: docker
    volumes:
      - /var/lib/postgres

  server:
    build: ./packages/server
    container_name: sigbba-node-container
    ports:
      - '3333:3333'
      - '9229:9229'
    volumes:
      - ./packages/server:/usr/app
      - ./node_modules:/usr/app/node_modules
    depends_on:
      - db

  web:
    build: ./packages/web
    container_name: sigbba-web-container
    ports:
      - 3000:3000
    volumes:
      - ./packages/web:/usr/app
      - ./node_modules:/usr/app/node_modules

networks:
  default:
    external: true
    name: my-network
