version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: sigbba-postgres-container
    ports:
      - 5432:5432/tcp
    environment:
      POSTGRES_DB: sigbba
      POSTGRES_USER: root
      POSTGRES_PASSWORD: docker
    volumes:
      - /var/lib/postgres
    deploy:
      resources:
        limits:
          memory: 1024M
        reservations:
          memory: 512M

  server:
    build: ./packages/server
    container_name: sigbba-node-container
    ports:
      - '3333:3333'
      - '9229:9229'
    volumes:
      - ./packages/server:/usr/app
      - ./node_modules:/usr/app/node_modules
    depends_on:
      - db
    links:
      - db
    deploy:
      resources:
        limits:
          memory: 1024M
        reservations:
          memory: 512M

  web:
    build: ./packages/web
    container_name: sigbba-web-container
    ports:
      - 3000:3000
    volumes:
      - ./packages/web:/usr/app
      - ./node_modules:/usr/app/node_modules
    deploy:
      resources:
        limits:
          memory: 1024M
        reservations:
          memory: 512M
